server:
  port: 20080

logging:
  path: log

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    name: sflc
    #dev
#    url: jdbc:oracle:thin:@192.168.100.10:1521:prod
#    username: sflcgood20200710
#    password: sflcgood20200710
    #pro
        url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.102.182)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.102.183)(PORT = 1521))(LOAD_BALANCE = yes)(FAILOVER = ON)(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = sflcdb)(FAILOVER_MODE=(TYPE = SELECT)(METHOD = BASIC)(RETIRES = 20)(DELAY = 15))))
        username: sflcgood
        password: sflcgood
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
